# Generated by Django 4.1.5 on 2023-01-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agriculture', '0002_auto_20230124_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='machinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=122)),
                ('date', models.DateField()),
                ('qty', models.IntegerField()),
                ('machinery', models.CharField(max_length=122)),
            ],
        ),
    ]
