# Generated by Django 4.1.5 on 2023-01-24 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agriculture', '0003_machinery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinery',
            name='qty',
        ),
    ]
