# Generated by Django 4.1.5 on 2023-01-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agriculture', '0004_remove_machinery_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinery',
            name='machinery',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='partner_name',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
