# Generated by Django 4.1.5 on 2023-01-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agriculture', '0008_alter_machinery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=122, null=True)),
                ('seeds', models.CharField(max_length=122, null=True)),
                ('date', models.DateField(null=True)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=122, null=True)),
                ('seeds', models.CharField(max_length=122, null=True)),
                ('date', models.DateField(null=True)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
    ]
