# Generated by Django 4.1.5 on 2023-01-24 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agriculture', '0009_crops_seeds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crops',
            old_name='amount',
            new_name='amt_bags',
        ),
        migrations.RenameField(
            model_name='crops',
            old_name='seeds',
            new_name='crops',
        ),
    ]
