# Generated by Django 4.1.5 on 2023-01-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agriculture', '0011_purchase_crops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='date_requested',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='status',
        ),
        migrations.AddField(
            model_name='loan',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_req',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_returned',
            field=models.IntegerField(null=True),
        ),
    ]
