# Generated by Django 4.1.5 on 2023-01-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agriculture', '0012_remove_loan_amount_remove_loan_date_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
