# Generated by Django 4.1.5 on 2023-01-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agriculture', '0013_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
