# Generated by Django 4.1.5 on 2023-01-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agriculture', '0015_alter_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.BooleanField(default='Not Accepted', null=True),
        ),
    ]
