# Generated by Django 4.1.5 on 2023-01-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agriculture', '0017_alter_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='rent',
            field=models.IntegerField(null=True),
        ),
    ]
